medcentre/apps/medcentreApp/urls.py
from django.urls import path

from . import views

app_name = "medcentreApp"
urlpatterns = [
    path('', views.index, name = '_index_'),
    path('<int:article_id>/', views.det, name='det'),
        path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment')
]

medcentre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include

urlpatterns = [
    path('medcentreApp/', include('medcentreApp.urls')),
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
]

medcentre/apps/medcentreApp/models.py
import datetime

from django.db import models
from django.utils import timezone

class Article(models.Model):
    art_title = models.CharField('название статьи', max_length = 200)
    art_text = models.TextField('содержимое статьи')
    pub_date = models.DateTimeField('дата публикации')

    def __str__(self):
        return self.art_title

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=7))

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class Comment(models.Model):
    art = models.ForeignKey(Article, on_delete = models.CASCADE)
    author_name = models.CharField('автор коммента', max_length = 50)
    comment_text = models.CharField('текст коммента', max_length = 200)

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

        

medcentre/apps/medcentreApp/views.py
from audioop import reverse
import imp
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from .models import Article
from django.urls import reverse

def index(request):
    latest_articles_list = Article.objects.order_by('-pub_date')[:5]
    return render(request, 'medcentreApp/list.html', {'latest_articles_list': latest_articles_list})

def det(request, article_id):
    try:
        a = Article.objects.get(id = article_id)
    except:
        raise Http404("No Articles Found!")

    latest_comments_list = a.comment_set.order_by('-id')[:10]
    return render(request, 'medcentreApp/det.html', {'article': a, 'latest_comments_list':latest_comments_list})

def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id = article_id)
    except:
        raise Http404("No Articles Found!")
    a.comment_set.create(author_name = request.POST['name'], comment_text = request.POST['text'])

    return HttpResponseRedirect(reverse('medcentreApp:det', args = (a.id,)))

medcentre/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">   
        <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'css/medcentreApp.css' %}">
        <meta charset="UTF=8">
        <title>{% block title%} My Site {% endblock %}</title>
    </head>
    <body>
        {% block content%} {% endblock %}
    </body>
</html>

medcentre/templates/medcentreApp/det.html
{% extends 'base.html' %}

{% block title %} {{article.art_title}} {% endblock %}

{% block content %} 
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                <div class="article">
                    <h2> {{article.art_title}} </h2>
                    <p>{{article.art_text}}</p>
                    <div class="date">
                        <em>{{article.pub_date}}</em>
                        {%if article.was_published_recently%}
                            New Article!
                        {%endif%}
                    </div>
                </div>
                <hr>
            
                {% if latest_comments_list %}
                    {%for c in latest_comments_list%}
                    <p>
                        <strong>{{c.author_name}}</strong>
                        <p>{{c.comment_text}}</p>
                    </p>
                    {%endfor%}
                {%else%}
                No comments found...
                {%endif%}
            
                <hr>
                <form action="{% url 'medcentreApp:leave_comment' article.id %}" method="POST">
                    {% csrf_token %}
                    <input type="text" required="" placeholder="Your Name" name="name"><br>
                    <textarea name="text" required="" placeholder="Text of your comment" cols="30" rows="10"></textarea><br>
                    <button type="submit">Leave comment</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

medcentre/templates/medcentreApp/list.html
{% extends 'base.html' %}

{% block title %} Recent Articles {% endblock %}

{% block content %} 
    {% if latest_articles_list %}
        <div class="page-header">
            <h1>Статьи</h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% for a in latest_articles_list %}
                        <h2><a href="{% url 'medcentreApp:det' a.id %}">{{ a.art_title }}</a></h2>
                        <p>{{ a.pub_date }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>
        
    {%else%}
        No Articles found :(
    {% endif %}
{% endblock %}